### PR TITLE
[134] Add box with a message if no submissions to show

### PR DESCRIPTION
**Pull request by przemyslawhaptas**

### CODE REVIEW

**Comment by przemyslawhaptas** [comment]
screen shot 2017-02-28 at 11 25 33

**Comment by lesniakania** [comment]
Why there is `1` displayed in the message there?

**Comment by przemyslawhaptas** [comment]
Cause it's in a table row and the table is styled in css so that it shows row numbers

**Comment by lesniakania** [comment]
So maybe it should not be in the table row ; ] I mean, this number looks weird, it would be good to not have it.

**Comment by szynszyliszys** [comment]
@lesniakania I moved it to the div in here https://github.com/LunarLogic/rails-girls-submissions/commit/ebb30c743668278a7c2275df76694aebee51a94c

**Comment by lesniakania** [comment]
<3

**Pull request merged**
