### PR TITLE
[154] Remove underscores from invitation_status

### PR DESCRIPTION
**Pull request by przemyslawhaptas**

### CODE REVIEW

**Comment by lesniakania** [comment]
Usually, I do statuses as symbols and with underscores, but I add some mapping (even as a simple hash) from statuses to displayed statuses. This is comment for future, don't change it now ; ]
But it will be good for you to read this: http://www.gaurishsharma.com/2013/04/understanding-differences-between-symbols-strings-in-ruby.html

**Comment by przemyslawhaptas** [comment]
Thanks for the link, didn't know that!
And now that I look at the presenter... Don't you think the invitation status shouldn't be responsible for it? What do you think about moving it to the model (the symbols with underscores version) and only controlling it's appearance in the presenter?

**Comment by lesniakania** [comment]
Sounds good :]

**Comment by przemyslawhaptas** [comment]
[Move `invitation_status` to the model, control appearance in the presenter](https://trello.com/c/hksCTVCg/175-move-invitation-status-to-the-model-control-appearance-in-the-presenter)

**Pull request merged**
